version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - env | grep APP_ | sed -e "s/^APP_//" > .env
      - pip install -r requirements.txt
# Include only the files required for your application to run.
artifacts:
  files:
    - "**/*"
